[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "9w6Bay8y3yDdQzPLH8h4ygBQqDBDHjQEr3U2KqQHec9B"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
